# Generated by Django 5.0.7 on 2024-09-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('weight', models.IntegerField()),
                ('tall', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('subscription_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
